### ISSUE TITLE
Failed to upload file to database on heroku website

### ISSUE THREAD

**Issue by snlongmore** [camelot-project/database#79]
Tried to upload a file with the following text to the heroku website:
# name,ID,R[pc],V[km/s],SurfDens[Msun/pc^2]

MarkSwinbank,1,110.,45.,1.0e+04
MarkSwinbank,2,116.,82.,2.2e+04
MarkSwinbank,3,105.,63.,4.0e+04
MarkSwinbank,4,160.,74.,2.8e+04
MarkSwinbank,5,300.,56.,8.6e+03

Here is the text I entered:

![screen shot 2015-05-26 at 10 13 15](https://cloud.githubusercontent.com/assets/12394899/7812908/3f3c0dfc-03ae-11e5-8b5a-eeefd0a30ac7.png)

I get the standard "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.” error message when I hit submit.

**Comment by keflavich** [comment]
@snlongmore if you open the "Inspector" using chrome, safari, or firefox, and you look at the Javascript console (I can help you find this if needed), do you see errors popping up?

Does the latest version work with https://github.com/camelot-project/frontend/pull/96 included?

(also, I was wrong, this is a frontend issue, not a database issue)

**Comment by jmdkastro** [comment]
@snlongmore Maybe the server didn't like the reference ;) ...shouldn't it be http://adsabs.harvard.edu/abs/2011ApJ...742...11S?

**Comment by snlongmore** [comment]
@jmdkastro very true! Good spot. Clearly there is no way to get around user error here. Perhaps a function to automatically recognise the paper from the data...just kidding @keflavich!

**Comment by snlongmore** [comment]
Sorry @keflavich but I broke it again. Tried to upload snl_bolatto_08.csv and got the same error again. Here is the screen shot of the input

![screen shot 2015-05-26 at 16 35 09](https://cloud.githubusercontent.com/assets/12394899/7816310/63bc3aa0-03c5-11e5-8d59-cbc9639ebbc5.png)

**Comment by snlongmore** [comment]
Weird!!! When I go to the Heroku website and try to query the database it says the Bolatto data is there... is this related to my above issue??

**Comment by agianne** [comment]
Similar problem here. I tried to upload my dataset and it told me that there was no difference with the current version of the database, but on query it shows my dataset as well!

**Comment by keflavich** [comment]
@agianne - that means your data set was already included in the database, I think?

**Comment by agianne** [comment]
@keflavich It would seem so. However I checked the query page before submitting and it was not there. I don't understand what's happened there

**Comment by keflavich** [comment]
Neither do I.  Something is wrong with the database on the heroku server.   I'll investigate.

**Comment by keflavich** [comment]
@agianne I think it is probably fixed now.  Could you give it a try in >2 minutes?

**Comment by agianne** [comment]
Tested again. I did not enter the ADS ID, but just the DOI and I got an internal server error. The data set was uploaded anyway.

**Comment by keflavich** [comment]
could you save your upload form and take a screenshot?  

Your database was not successfully uploaded - there is no new pull request.

**Comment by agianne** [comment]
I noticed - but I see my data in the query!
![2015-05-29-123214_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12412544/7881130/e6b79a6c-05ff-11e5-90bd-6f35cb287170.png)
This is the error I get:
![2015-05-29-123345_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12412544/7881136/f404c1ea-05ff-11e5-838c-276ea014af37.png)
and finally the query results:
![2015-05-29-123551_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12412544/7881138/fb561caa-05ff-11e5-82b6-3c085e8028f3.png)

**Comment by keflavich** [comment]
I think this means that the cleanup stage failed, which is very bad.

**Comment by keflavich** [comment]
@agianne I'm deploying another attempt at a solution.  I still don't understand what's causing your underlying problem, but I should have cured enough of the symptoms to now see past them.

**Comment by agianne** [comment]
@keflavich same error. At least I don't see my dataset in the query!
![2015-05-29-144233_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12412544/7882845/e4d0c734-0611-11e5-838e-63a100ff4dce.png)

**Comment by keflavich** [comment]
The problem seems to be that the table did not read correctly.  However, I can't reproduce your error; I get:

```
There has been a server-side error:
The value must be a valid Python or Numpy numeric type.
Traceback (most recent call last): File "upload_form.py", line 306, in set_columns convert_units(table) File "/Users/adam/repos/camelot_frontend/ingest_datasets_better.py", line 93, in convert_units tbl[k] = tbl[k].to(v) File "/Users/adam/repos/astropy/astropy/table/column.py", line 688, in to return self.quantity.to(unit, equivalencies) File "/Users/adam/repos/astropy/astropy/table/column.py", line 666, in quantity return Quantity(self, copy=False, dtype=self.dtype, order='A') File "/Users/adam/repos/astropy/astropy/units/quantity.py", line 243, in __new__ raise TypeError("The value must be a valid Python or " TypeError: The value must be a valid Python or Numpy numeric type.
```

**Comment by agianne** [comment]
Try to remove the header line with the units (https://github.com/camelot-project/frontend/issues/45)

**Comment by e-koch** [comment]
I'm also getting the same error as @agianne.

**Comment by e-koch** [comment]
Can confirm that [frontend #104](https://github.com/camelot-project/frontend/pull/104) appears to fix this issue.

**Comment by snlongmore** [comment]
So I just tried to upload a file to the database for Lisa Wei's data and got the following error 

![screen shot 2015-06-09 at 10 13 19](https://cloud.githubusercontent.com/assets/12394899/8054468/d6841438-0e90-11e5-82e6-818c248d7b70.png)

I checked and found there was actually still a PR #82 for that data set from when I tried a few weeks ago, so I thought this might explain the error. However, I then checked closely and see I left a space between the first and last name, i.e. "Lisa Wei" instead of "LisaWei". I then repeated the upload removing the space and it seems to have worked fine. This rules out the previous attempt at submitting this data set from causing the problem. If it is the "space" problem, I suspect this may be a common mistake. It would be good to (i) add a warning message about this on the upload page, (ii) not let the person submit if there is a whitespace in the name field.

**Comment by snlongmore** [comment]
I just tried to upload Mark Heyer's data with these parameters

![screen shot 2015-06-09 at 11 09 59](https://cloud.githubusercontent.com/assets/12394899/8055538/2463fe32-0e98-11e5-869b-c7e2c478c07c.png)

and got the following error:

![screen shot 2015-06-09 at 11 08 22](https://cloud.githubusercontent.com/assets/12394899/8055520/fc6c3c0a-0e97-11e5-899e-be0eb12c8fc6.png)

Not sure what went wrong there -- I can't see anything obviously stupid with the values I put in...

A PR was not created.
